events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name dev.ergominers.com;
        
        location / {
            proxy_pass http://dash:8050;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /miner-id-minter/ {
            proxy_pass http://miner-id-minter:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Default server block to handle requests for unknown server names
    server {
        listen 80 default_server;
        server_name _;
        return 444;
    }
}
